name: LGTM Reaction
on:
  pull_request_review:
    types: [submitted]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1.0.0
      - uses: micnncim/action-lgtm-reaction@v0.5.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_COMMENT_BODY: ${{ github.event.comment.body }}
          GITHUB_COMMENT_ID: ${{ github.event.comment.id }}
          GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REVIEW_BODY: ${{ github.event.review.body }}
          GITHUB_REVIEW_ID: ${{ github.event.review.id }}
        with:
          trigger: '["^LGTM!?$"]'
          override: true
          source: lgtmapp
